# Generated by Django 5.2.7 on 2025-10-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("test", "Test"), ("course", "Course")], max_length=20
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("kakaopay", "KakaoPay"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("cancelled", "Cancelled")],
                        default="paid",
                        max_length=20,
                    ),
                ),
                ("refund_reason", models.TextField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="idx_payment_user_status"
                    ),
                    models.Index(fields=["paid_at"], name="idx_payment_paid_at"),
                    models.Index(
                        fields=["status", "paid_at"], name="idx_payment_status_date"
                    ),
                ],
            },
        ),
    ]
