# Generated by Django 5.2.7 on 2025-10-25 09:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="idx_course_search"
            ),
        ),
    ]
