# Generated by Django 5.2.7 on 2025-10-27 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_search_vector_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="courseregistration",
            index=models.Index(fields=["course"], name="idx_course_reg_course"),
        ),
    ]
