# Generated by Django 5.2.7 on 2025-10-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_courseregistration_idx_course_reg_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrollment_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
