# Generated by Django 5.2.7 on 2025-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_rename_enrollment_count_to_registration_count"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-registration_count", "-created_at"], name="idx_course_popular"
            ),
        ),
    ]
