# Generated by Django 5.2.7 on 2025-10-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tests",
                "indexes": [
                    models.Index(fields=["start_at", "end_at"], name="idx_test_dates"),
                    models.Index(fields=["-created_at"], name="idx_test_created"),
                    models.Index(
                        fields=["start_at", "end_at", "-created_at"],
                        name="idx_test_composite",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TestRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tests.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "test_registrations",
                "indexes": [
                    models.Index(fields=["user", "test"], name="idx_test_reg_unique"),
                    models.Index(fields=["status"], name="idx_test_reg_status"),
                    models.Index(fields=["user"], name="idx_test_reg_user"),
                ],
                "unique_together": {("user", "test")},
            },
        ),
    ]
