# Generated by Django 5.2.7 on 2025-10-25 07:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_enable_fts"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="idx_test_search"
            ),
        ),
    ]
