# Generated by Django 5.2.7 on 2025-10-27 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_add_search_vector_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testregistration",
            index=models.Index(fields=["test"], name="idx_test_reg_test"),
        ),
    ]
