# Generated by Django 5.2.7 on 2025-10-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_testregistration_idx_test_reg_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="registration_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
