# Generated by Django 5.2.7 on 2025-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_test_registration_count"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["-registration_count", "-created_at"], name="idx_test_popular"
            ),
        ),
    ]
